version: '3.3'
services:
  api:
    container_name: 'api'
    restart: 'always'
    build: './api'
    ports:
      - '3000:3000'
    env_file:
      - '.env'    
    volumes:
      - './api:/go/src/app'
    depends_on:
      - 'mongo'
  mongo:
    image: 'mongo'
    restart: 'always'
    ports:
      - '27017:27017'